### ISSUE TITLE
Comply with GitHub 

### ISSUE THREAD

**Issue by 0xWDG** [AuroraEditor/Aurora-Editor-Bot#29]
https://docs.github.com/en/webhooks/using-webhooks/best-practices-for-using-webhooks

send 200 back (already done) and send a ` X-GitHub-Delivery` header.

**Comment by aurora-care-bear** [comment]
Thanks for submitting a issue!
to assign this issue to yourself please comment `@aurora-editor-bot please assign me`

**Comment by 0xWDG** [comment]
fixed in https://github.com/AuroraEditor/Aurora-Editor-Bot/commit/42fea0dda1d57d2119e5ecdb4d1334c1970b7d37
