### ISSUE TITLE
Bot does assign if you used a blockquote

### ISSUE THREAD

**Issue by 0xWDG** [AuroraEditor/Aurora-Editor-Bot#30]
Bot does assign if you used a blockquote

**Comment by aurora-care-bear** [comment]
Thanks for submitting a issue!
to assign this issue to yourself please comment `@aurora-care-bear please assign me`

**Comment by 0xWDG** [comment]
@aurora-care-bear please assign me 🩵

**Comment by 0xWDG** [comment]
> @aurora-care-bear please assign me 🩵

You should ignore this, because it's in a block quote.

**Comment by 0xWDG** [comment]
:[

**Comment by 0xWDG** [comment]
> > @aurora-care-bear please assign me 🩵
> 
> You should ignore this, because it's in a block quote.

This should work right now after https://github.com/AuroraEditor/Aurora-Editor-Bot/commit/20275e25af130119a6fd29a41e722374d53959e5

**Comment by 0xWDG** [comment]
> > > @aurora-care-bear please assign me 🩵
> > 
> > 
> > You should ignore this, because it's in a block quote.
> 
> This should work right now after [20275e2](https://github.com/AuroraEditor/Aurora-Editor-Bot/commit/20275e25af130119a6fd29a41e722374d53959e5)

Nice.

@aurora-care-bear please assign me

**Comment by 0xWDG** [comment]
@nanashili Fixed.

**Comment by nanashili** [comment]
> @aurora-care-bear please assign me 🩵 

Nice
